/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaprincipal;

import capadenegocio.GestorPrincipal;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.UtilSwing;
import vista.asociar.JpanAsociarLibroaFac;
import vista.asociar.JpanAsociarUsuaFac;
import vista.facultades.JpanListarLibrosdeFacultades;
import vista.facultades.JpanListarUsuariosdeFacultades;
import vista.facultades.JpanRegistrarFacultad;
import vista.libro.JpanBuscarLibros;
import vista.libro.JpanListaDeLibros;
import vista.libro.JpanRegistrarLibros;
import vista.libro.jPanDevolverLibro;
import vista.libro.jpanListarLibrosPrestados;
import vista.usuario.JpanBuscarUsuario;
import vista.usuario.JpanListaDeUsuarios;
import vista.usuario.JpanRegistrarUsuario;

/**
 *
 * @author THINKPAD
 */
public class JfrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JfrmPrincipal
     */
    public JfrmPrincipal() {
        initComponents();
        iniciarComponentes();
    }

    public void iniciarComponentes() {
        setLocationRelativeTo(null);
        setResizable(false);
        setVisible(true);
        jPanel1.setLayout(new FlowLayout());
    }
    
    
    
    public void animar() {
        int i = 1;
        while (i < 6) {
          //  panelima.setIcon(imagenes[i]);
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                System.out.println("error");
            }
            
            i++;
            if (i == 6) {
                i = 1;
            }
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuLibros = new javax.swing.JMenu();
        jmIReglib = new javax.swing.JMenuItem();
        jmIListLib = new javax.swing.JMenuItem();
        JMIbusLib = new javax.swing.JMenuItem();
        MenuUsuarios = new javax.swing.JMenu();
        jmiRegUsu = new javax.swing.JMenuItem();
        JMILisUsu = new javax.swing.JMenuItem();
        JMIBusUsu = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMIRegFac = new javax.swing.JMenuItem();
        JMILisLibdeFac = new javax.swing.JMenuItem();
        JMILisUsudeFac = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMIAsocLibaFac = new javax.swing.JMenuItem();
        JMIAsocUsuaFac = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMIListarLibrosPrestados = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(115, 187, 187));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        MenuLibros.setText("Libros");

        jmIReglib.setText("Registrar");
        jmIReglib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIReglibActionPerformed(evt);
            }
        });
        MenuLibros.add(jmIReglib);

        jmIListLib.setText("Listar");
        jmIListLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmIListLibActionPerformed(evt);
            }
        });
        MenuLibros.add(jmIListLib);

        JMIbusLib.setText("Buscar");
        JMIbusLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIbusLibActionPerformed(evt);
            }
        });
        MenuLibros.add(JMIbusLib);

        jMenuBar1.add(MenuLibros);

        MenuUsuarios.setText("Usuarios");

        jmiRegUsu.setText("Registrar");
        jmiRegUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegUsuActionPerformed(evt);
            }
        });
        MenuUsuarios.add(jmiRegUsu);

        JMILisUsu.setText("Listar");
        JMILisUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILisUsuActionPerformed(evt);
            }
        });
        MenuUsuarios.add(JMILisUsu);

        JMIBusUsu.setText("Buscar");
        JMIBusUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIBusUsuActionPerformed(evt);
            }
        });
        MenuUsuarios.add(JMIBusUsu);

        jMenuBar1.add(MenuUsuarios);

        jMenu3.setText("Facultades");

        JMIRegFac.setText("Registrar");
        JMIRegFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIRegFacActionPerformed(evt);
            }
        });
        jMenu3.add(JMIRegFac);

        JMILisLibdeFac.setText("Listar libros");
        JMILisLibdeFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILisLibdeFacActionPerformed(evt);
            }
        });
        jMenu3.add(JMILisLibdeFac);

        JMILisUsudeFac.setText("Listar Usuarios");
        JMILisUsudeFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMILisUsudeFacActionPerformed(evt);
            }
        });
        jMenu3.add(JMILisUsudeFac);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Asociar");

        JMIAsocLibaFac.setText("Asociar Libro a Facultad");
        JMIAsocLibaFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAsocLibaFacActionPerformed(evt);
            }
        });
        jMenu4.add(JMIAsocLibaFac);

        JMIAsocUsuaFac.setText("Asociar Usuario a Facultad");
        JMIAsocUsuaFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAsocUsuaFacActionPerformed(evt);
            }
        });
        jMenu4.add(JMIAsocUsuaFac);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Libros Prestados");

        JMIListarLibrosPrestados.setText("Listar");
        JMIListarLibrosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIListarLibrosPrestadosActionPerformed(evt);
            }
        });
        jMenu2.add(JMIListarLibrosPrestados);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Devolver Libro");

        jMenuItem1.setText("Devolver Libro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmIListLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIListLibActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanListaDeLibros());        // TODO add your handling code here:
    }//GEN-LAST:event_jmIListLibActionPerformed

    private void jmiRegUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegUsuActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanRegistrarUsuario());        // TODO add your handling code here:
    }//GEN-LAST:event_jmiRegUsuActionPerformed

    private void JMILisUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILisUsuActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanListaDeUsuarios()); // TODO add your handling code here:
    }//GEN-LAST:event_JMILisUsuActionPerformed

    private void JMILisUsudeFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILisUsudeFacActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanListarUsuariosdeFacultades());  // TODO add your handling code here:
    }//GEN-LAST:event_JMILisUsudeFacActionPerformed

    private void jmIReglibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmIReglibActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanRegistrarLibros());        // TODO add your handling code here:
    }//GEN-LAST:event_jmIReglibActionPerformed

    private void JMIbusLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIbusLibActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanBuscarLibros());        // TODO add your handling code here:
    }//GEN-LAST:event_JMIbusLibActionPerformed

    private void JMIBusUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIBusUsuActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanBuscarUsuario());        // TODO add your handling code here:
    }//GEN-LAST:event_JMIBusUsuActionPerformed

    private void JMIRegFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIRegFacActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanRegistrarFacultad());        // TODO add your handling code here:
    }//GEN-LAST:event_JMIRegFacActionPerformed

    private void JMILisLibdeFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMILisLibdeFacActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanListarLibrosdeFacultades());        // TODO add your handling code here:
    }//GEN-LAST:event_JMILisLibdeFacActionPerformed

    private void JMIAsocLibaFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAsocLibaFacActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanAsociarLibroaFac());        // TODO add your handling code here:
    }//GEN-LAST:event_JMIAsocLibaFacActionPerformed

    private void JMIAsocUsuaFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAsocUsuaFacActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new JpanAsociarUsuaFac());        // TODO add your handling code here:
    }//GEN-LAST:event_JMIAsocUsuaFacActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea guardar los cambios efectuados?", "Guardar", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            boolean estado = GestorPrincipal.getGestorBasedeDatos().guardarCambios();
        } else if (respuesta == JOptionPane.NO_OPTION) {
        }  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void JMIListarLibrosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIListarLibrosPrestadosActionPerformed
        UtilSwing.colocarNuevoPanel(jPanel1, new jpanListarLibrosPrestados());
    }//GEN-LAST:event_JMIListarLibrosPrestadosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 UtilSwing.colocarNuevoPanel(jPanel1, new jPanDevolverLibro());         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIAsocLibaFac;
    private javax.swing.JMenuItem JMIAsocUsuaFac;
    private javax.swing.JMenuItem JMIBusUsu;
    private javax.swing.JMenuItem JMILisLibdeFac;
    private javax.swing.JMenuItem JMILisUsu;
    private javax.swing.JMenuItem JMILisUsudeFac;
    private javax.swing.JMenuItem JMIListarLibrosPrestados;
    private javax.swing.JMenuItem JMIRegFac;
    private javax.swing.JMenuItem JMIbusLib;
    private javax.swing.JMenu MenuLibros;
    private javax.swing.JMenu MenuUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmIListLib;
    private javax.swing.JMenuItem jmIReglib;
    private javax.swing.JMenuItem jmiRegUsu;
    // End of variables declaration//GEN-END:variables
}
