/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaprincipal;

import capadenegocio.GestorPrincipal;
import entidad.Bibliotecario;
import entidad.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import util.UtilArchivo;

/**
 *
 * @author THINKPAD
 */
public class JfrmIniciodeSesion extends javax.swing.JFrame {

    /**
     * Creates new form JfrmIniciodeSesion
     */
    public JfrmIniciodeSesion() {

        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxfUsuario = new javax.swing.JTextField();
        jpsfContra = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtnIngresar = new javax.swing.JButton();
        jlblImag = new javax.swing.JLabel();
        jcbTipoDeIngreso = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario       :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña :");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingresar como:");

        jbtnIngresar.setText("Ingresar");
        jbtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarActionPerformed(evt);
            }
        });

        jlblImag.setBackground(new java.awt.Color(0, 204, 153));
        jlblImag.setForeground(new java.awt.Color(255, 255, 255));

        jcbTipoDeIngreso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bibliotecario", "Usuario" }));
        jcbTipoDeIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoDeIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblImag, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jcbTipoDeIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpsfContra)
                                    .addComponent(jtxfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblImag, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jpsfContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbTipoDeIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnIngresar))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbTipoDeIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoDeIngresoActionPerformed
        ImageIcon imagen;
        if (jcbTipoDeIngreso.getSelectedIndex() == 0) {
            jtxfUsuario.setVisible(true);
            jpsfContra.setVisible(true);
            jLabel3.setVisible(true);
            jLabel2.setVisible(true);
            imagen = new ImageIcon("bibliotecario.jpg");
        } else {
            jtxfUsuario.setVisible(false);
            jpsfContra.setVisible(false);
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            imagen = new ImageIcon("Usuario.jpg");
        }
        jlblImag.setIcon(imagen);
    }//GEN-LAST:event_jcbTipoDeIngresoActionPerformed

    private void jbtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarActionPerformed
        if (jcbTipoDeIngreso.getSelectedItem() == "Usuario") {
            JfrmUsuario jfrmUsuario = new JfrmUsuario();
            setVisible(false);
            GestorPrincipal.getGestorBasedeDatos().cargarArchivos();
        } else {
            String nombreUsuario = jtxfUsuario.getText();
            String password = jpsfContra.getText();

            Bibliotecario bibliotecario = new Bibliotecario();
            bibliotecario.setNombreBibliotecario(nombreUsuario);
            bibliotecario.setPassword(password);

            /*Usamos el "GestorUsuario" para validar los datos*/
            boolean estado = GestorPrincipal.getGestorBibliotecario().iniciarSesion(bibliotecario);
            if (estado == true) {
                JOptionPane.showMessageDialog(this, "BIENVENIDO\n"
                        + "BIBLIOTECARIO", "Sistema", JOptionPane.INFORMATION_MESSAGE);
                BarraProgreso bp = new BarraProgreso();
                this.setVisible(false);
                bp.setVisible(true);
                bp.setLocationRelativeTo(null);
                bp.setTitle("progreso..");
                bp.empezar();
            } else {
                JOptionPane.showMessageDialog(this, "El usuario y contraseña no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jbtnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JfrmIniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JfrmIniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JfrmIniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JfrmIniciodeSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
//                new JfrmIniciodeSesion().setVisible(true);
//                
//                
//            }
//        });
        JfrmIniciodeSesion jfrmis = new JfrmIniciodeSesion();
        jfrmis.setVisible(true);
        jfrmis.setLocationRelativeTo(null);
        jfrmis.setResizable(false);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnIngresar;
    private javax.swing.JComboBox jcbTipoDeIngreso;
    private javax.swing.JLabel jlblImag;
    private javax.swing.JPasswordField jpsfContra;
    private javax.swing.JTextField jtxfUsuario;
    // End of variables declaration//GEN-END:variables

    public void inicializar() {
        ImageIcon imagen;
        imagen = new ImageIcon("bibliotecario.jpg");
        jlblImag.setIcon(imagen);
    }

    public void animar() {
        int i = 1;
        while (i < 6) {
            // panelima.setIcon(imagenes[i]);
            try {
                Thread.sleep(2000);
            } catch (InterruptedException ex) {
                System.out.println("error");
            }

            i++;
            if (i == 6) {
                i = 1;
            }
        }

    }
}
