/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.usuario;

import capadenegocio.GestorPrincipal;

import entidad.Usuario;
import javax.swing.JOptionPane;
import util.UtilSwing;

/**
 *
 * @author THINKPAD
 */
public class JpanRegistrarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form JpanRegistrarUsuario
     */
    public JpanRegistrarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtxfCodigo = new javax.swing.JTextField();
        jtxfNombre = new javax.swing.JTextField();
        jtxfDNI = new javax.swing.JTextField();
        jtxfApPaterno = new javax.swing.JTextField();
        jtxfApMaterno = new javax.swing.JTextField();

        jLabel1.setText("Registrar Usuarios");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("DNI");

        jLabel5.setText("Ap. Paterno");

        jLabel6.setText("Ap Materno");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jtxfApPaterno))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxfCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                            .addComponent(jtxfNombre)
                                            .addComponent(jtxfDNI, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(20, 20, 20)
                                        .addComponent(jtxfApMaterno)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxfApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxfApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Leemos los datos del usuario*/
        Usuario usuario = new Usuario();
        usuario.setAp_materno(jtxfApMaterno.getText());
        usuario.setAp_paterno(jtxfApPaterno.getText());
        usuario.setCodigo(jtxfCodigo.getText());
        usuario.setDni(jtxfDNI.getText());
        usuario.setNombre(jtxfNombre.getText());

        /*Validamos los datos, usamos la versión resumida del "if-else" anidado*/
        if (usuario.getAp_materno().trim().equals("") == true) {
            System.out.println("El Ap.Materno no puede estar vacío");
        } else if (usuario.getAp_paterno().trim().equals("") == true) {
            System.out.println("El Ap.Paterno no puede estar vacío");
        } else if (usuario.getCodigo().trim().equals("") == true) {
            System.out.println("El codigo no puede estar vacío");
        } else if (usuario.getDni().trim().equals("") == true) {
            System.out.println("El DNI no puede estar vacío");
        } else if (usuario.getNombre().trim().equals("") == true) {
            System.out.println("El nombre no puede estar vacío");
        } else {
            /*Si pasamos todas las validaciones, lo registramos*/
            boolean estado = GestorPrincipal.getGestorUsuario().registrarUsuario(usuario);
            if (estado == true) {
                JOptionPane.showMessageDialog(this, "¡Usuario registrado con éxito!", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                UtilSwing.quitarPanel(this);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo registrar al usuario, verifique que no esté ya registrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtxfApMaterno;
    private javax.swing.JTextField jtxfApPaterno;
    private javax.swing.JTextField jtxfCodigo;
    private javax.swing.JTextField jtxfDNI;
    private javax.swing.JTextField jtxfNombre;
    // End of variables declaration//GEN-END:variables
}
