/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.libro;

import capadenegocio.GestorPrincipal;
import entidad.Libro;
import javax.swing.JOptionPane;
import util.UtilSwing;

/**
 *
 * @author THINKPAD
 */
public class JpanRegistrarLibros extends javax.swing.JPanel {

    /**
     * Creates new form JpanRegistrarcursos
     */
    public JpanRegistrarLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxfIsbn = new javax.swing.JTextField();
        jtxfNombre = new javax.swing.JTextField();
        jtxfAutor = new javax.swing.JTextField();
        jtxfTipo_de_libro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Registrar Libros");

        jLabel2.setText("Isbn:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Autor:");

        jLabel6.setText("Tipo de libro:");

        jtxfIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfIsbnActionPerformed(evt);
            }
        });

        jtxfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxfNombreActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxfTipo_de_libro)
                            .addComponent(jtxfIsbn)
                            .addComponent(jtxfNombre)
                            .addComponent(jtxfAutor))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 223, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxfTipo_de_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxfIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfIsbnActionPerformed

    private void jtxfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxfNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/*Leemos los datos del libro*/
        Libro libro = new Libro();
        libro.setAutor(jtxfAutor.getText());
        
        libro.setIsbn(jtxfIsbn.getText());
        libro.setNombre(jtxfNombre.getText());
        libro.setTipo_de_libro(jtxfTipo_de_libro.getText());

        /*Validamos los datos, usamos la versión resumida del "if-else" anidado*/
        if(libro.getIsbn().trim().equals("") == true){
            System.out.println("El ISBN no puede estar vacío");
        }else if(libro.getAutor().trim().equals("") == true){
            System.out.println("El autor no puede estar vacío");
        }else if(libro.getNombre().trim().equals("") == true){
            System.out.println("El nombre no puede estar vacío");
        }else if(libro.getTipo_de_libro().trim().equals("") == true){
            System.out.println("El tipo de libro no puede estar vacío");
        }else{
            /*Si pasamos todas las validaciones, lo registramos*/
            boolean estado = GestorPrincipal.getGestorLibro().agregarLibro(libro);
            if(estado == true){
                JOptionPane.showMessageDialog(this, "¡Libro registrado con éxito!", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                UtilSwing.quitarPanel(this);
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo registrar al libro, verifique que no esté ya registrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 UtilSwing.quitarPanel(this);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtxfAutor;
    private javax.swing.JTextField jtxfIsbn;
    private javax.swing.JTextField jtxfNombre;
    private javax.swing.JTextField jtxfTipo_de_libro;
    // End of variables declaration//GEN-END:variables
}
