/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.operacionesUsuario;

import capadenegocio.GestorPrincipal;
import entidad.Facultad;
import entidad.Libro;
import entidad.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import util.ComboItem;
import entidad.BaseDeDatos;
import util.UtilSwing;

/**
 *
 * @author Favio
 */
public class jPanPedirLibro extends javax.swing.JPanel {

    /**
     * Creates new form jPanPedirLibro
     */
    public jPanPedirLibro() {
        initComponents();
        jbpedir.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxfisbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxfCodigo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jbpedir = new javax.swing.JButton();

        jLabel1.setText("Pedido de libro");

        jLabel2.setText("ISBN del libro");

        jLabel4.setText("Codigo del Usuario");

        jtxfCodigo.setEditable(false);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbpedir.setText("Pedir");
        jbpedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel4)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxfisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jbpedir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxfisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addComponent(jbpedir)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String isbn = jtxfisbn.getText();
        Libro libro = GestorPrincipal.getGestorLibro().buscar(isbn);
        if (libro == null) {
            JOptionPane.showMessageDialog(this, "El libro con el isbn " + isbn + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            jbpedir.setVisible(true);
            jtxfCodigo.setEditable(true);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbpedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpedirActionPerformed
        String codigo = jtxfCodigo.getText();
        Usuario usuario = GestorPrincipal.getGestorUsuario().buscar(codigo);
        if (usuario == null) {
            JOptionPane.showMessageDialog(this, "El usuario con el codigo " + codigo + " no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String isbn = jtxfisbn.getText();
            Libro libro = GestorPrincipal.getGestorLibro().buscar(isbn);
            
            boolean estado = GestorPrincipal.getGestorLibro().agregarLibroPrestado(libro);
            if(estado == true){
                JOptionPane.showMessageDialog(this, "¡Libro prestado con éxito!", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                UtilSwing.quitarPanel(this);
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo registrar al libro, verifique que no esté ya registrado.", "Error", JOptionPane.ERROR_MESSAGE);
            }
//            GestorPrincipal.getGestorLibro().agregarLibroPrestado(libro);
//            JOptionPane.showMessageDialog(this, "El usuario con el codigo " + codigo + " pidio el libro" +isbn+" de isbn", "Libro Prestado", JOptionPane.INFORMATION_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jbpedirActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbpedir;
    private javax.swing.JTextField jtxfCodigo;
    private javax.swing.JTextField jtxfisbn;
    // End of variables declaration//GEN-END:variables
}
